# Autogenerated by devscripts/update-version.py

__version__ = '2024.12.11.193636'

RELEASE_GIT_HEAD = '2a246749ec5ead2c6b485e702a1c54c79bd0e51a'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'plun1331/yt-dlp'

ORIGIN = 'plun1331/yt-dlp'

_pkg_version = '2024.12.11.193636'
